# Generated by Django 2.0.2 on 2018-02-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20180207_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='library_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
