# Generated by Django 2.0.2 on 2018-02-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_auto_20180207_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='library_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
