# Generated by Django 2.0.2 on 2018-02-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servant',
            old_name='noble_phatasm',
            new_name='noble_phantasm',
        ),
    ]
